# Generated by Django 5.2.9 on 2026-01-07 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_project_client_alter_project_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.contract'),
        ),
    ]
