# Generated by Django 5.2.9 on 2026-01-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_contract_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
