# Generated by Django 5.2.9 on 2026-01-13 09:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='contract',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='accounts.contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
