# Generated by Django 5.2.9 on 2026-01-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_message_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
