# Generated by Django 5.2.9 on 2026-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_review_contract_review_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='useAvatar',
            field=models.BooleanField(default=False),
        ),
    ]
