# Generated by Django 5.2.9 on 2026-01-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
